### ISSUE TITLE
ErrorValueError: Found group index but no groupsize. What do?

### ISSUE THREAD

**Issue by bbecausereasonss** [shinomakoi/magi_llm_gui#4]
Traceback (most recent call last):
  File "C:\Users\xxxx\Deep\magi\magi_llm_app.py", line 786, in textgen_switcher
    self.load_model('llama.cpp')
  File "C:\Users\xxxx\Deep\magi\magi_llm_app.py", line 768, in load_model
    cpp_model = LlamaCppModel.from_pretrained(
  File "C:\Users\xxxx\Deep\magi\llamacpp_generate.py", line 12, in from_pretrained
    return cls(**params)
  File "C:\Users\xxxx\Deep\magi\llamacpp_generate.py", line 7, in __init__
    self.model = Llama(**params)
  File "C:\Users\xxxx\anaconda3\envs\magi\lib\site-packages\llama_cpp\llama.py", line 191, in __init__
    raise ValueError(f"Model path does not exist: {model_path}")
ValueError: Model path does not exist:
--- Loading Exllama model...
INFO: Could not find files for the given pattern(s).
Injected compiler path: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\bin\Hostx64\x64
E:\Backups\Deep Models\LLama\models\TheBloke_airoboros-33b-gpt4-GPTQ\gptq_model-4bit--1g.safetensors
Exception ignored in: <function Llama.__del__ at 0x0000021C1CA313F0>
Traceback (most recent call last):
  File "C:\Users\xxxx\anaconda3\envs\magi\lib\site-packages\llama_cpp\llama.py", line 1333, in __del__
    if self.ctx is not None:
AttributeError: 'Llama' object has no attribute 'ctx'
Traceback (most recent call last):
  File "C:\Users\xxxx\Deep\magi\magi_llm_app.py", line 788, in textgen_switcher
    self.load_model('Exllama')
  File "C:\Users\xxxx\Deep\magi\magi_llm_app.py", line 760, in load_model
    exllama_model = ExllamaModel.from_pretrained(
  File "C:\Users\xxxx\Deep\magi\exllama_generate.py", line 64, in from_pretrained
    model = ExLlama(config)
  File "C:\Users\xxxx\Deep\magi\exllama\model.py", line 759, in __init__
    layer = ExLlamaDecoderLayer(self.config, tensors, f"model.layers.{i}", i, sin, cos)
  File "C:\Users\xxxx\Deep\magi\exllama\model.py", line 345, in __init__
    self.self_attn = ExLlamaAttention(self.config, tensors, key + ".self_attn", sin, cos, self.index)
  File "C:\Users\xxxx\Deep\magi\exllama\model.py", line 257, in __init__
    self.q_proj = Ex4bitLinear(config, self.config.hidden_size, self.config.num_attention_heads * self.config.head_dim, False, tensors, key + ".q_proj")
  File "C:\Users\xxxx\Deep\magi\exllama\model.py", line 165, in __init__
    if self.groupsize is None: raise ValueError("Found group index but no groupsize. What do?")
ValueError: Found group index but no groupsize. What do?

**Comment by shinomakoi** [comment]
I can't replicate this error with the models I use but I found mention of it here: https://github.com/turboderp/exllama/issues/44. 
Are you on the latest Exllama commit, is apparently fixed now. Seems to happen only on certain models.
