### ISSUE TITLE
Error: ModuleNotFoundError: No module named 'diskcache'

### ISSUE THREAD

**Issue by bbecausereasonss** [shinomakoi/magi_llm_gui#6]
Built CPP with CUBLAS, tried to load model with 44 layers on a 4090

(magi) PS C:\Users\xxxx\Deep\magi> python .\magi_llm_app.py
--- Launched app
--- Loading llama.cpp model...
Traceback (most recent call last):
  File "C:\Users\xxxx\Deep\magi\magi_llm_app.py", line 786, in textgen_switcher
    self.load_model('llama.cpp')
  File "C:\Users\xxxx\Deep\magi\magi_llm_app.py", line 766, in load_model
    from llamacpp_generate import LlamaCppModel
  File "C:\Users\xxxx\Deep\magi\llamacpp_generate.py", line 1, in <module>
    from llama_cpp import Llama
  File "C:\Users\xxxx\anaconda3\envs\magi\lib\site-packages\llama_cpp\__init__.py", line 2, in <module>
    from .llama import *
  File "C:\Users\xxxx\anaconda3\envs\magi\lib\site-packages\llama_cpp\llama.py", line 21, in <module>
    import diskcache
ModuleNotFoundError: No module named 'diskcache'

**Comment by bbecausereasonss** [comment]
Fixed by pip install diskcache (maybe should be added to requirements)

**Comment by shinomakoi** [comment]
Thought that would be installed as a dependency. I added it to the requirements.txt
